version: '2'
services:
  puppet:
    image: webcenter/puppet-dev:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ./:$PWD
      - .:/etc/puppetlabs/code/modules/hm_centreon:ro
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=127.0.0.1,.test.local,10.221.78.61
    privileged: true
    hostname: puppet
    domainname: test.local
    working_dir: $PWD
    links:
      - centreon:centreon

  puppet-ci:
    image: webcenter/puppet-centreon:test
    build:
      context: ./
      dockerfile: .circleci/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=127.0.0.1,.test.local,10.221.78.61
    hostname: puppet
    domainname: test.local
    links:
      - centreon:centreon

  centreon:
    image: webcenter/centreon:latest
    ports:
      - 80:80
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ../centreon/www/class/centreon-clapi:/usr/share/centreon/www/class/centreon-clapi:ro
      - ../centreon/lib/Centreon:/usr/share/centreon/lib/Centreon:ro
    cap_add:
      - SYS_ADMIN
    tty: true


