# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker-compose up -d centreon-ci
          sleep 30
          docker-compose exec centreon-ci ps aux
          docker-compose exec centreon-ci curl -vvv http://127.0.0.1/centreon/install_finish.html
          docker-compose run --rm puppet-ci bash -c '/usr/bin/curl -vvv http://centreon/centreon/install_finish.html'
          docker-compose run puppet-ci bash -c 'rspec lib/centreon/*_spec.rb' &&\
          until $(docker-compose run --rm puppet-ci bash -c '/usr/bin/curl --head --fail --output /dev/null --silent http://centreon/centreon/install_finish.html'); do sleep 5; done &&\
          docker-compose run puppet-ci bash -c 'BEAKER_set=ci rspec spec/acceptance/*_spec.rb'
workflows:
  version: 2
  build-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/