# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby
    steps:
      - setup_remote_docker
      - checkout
      - run: docker-compose build puppet-ci
      - run: docker-compose run puppet-ci bash -c 'rspec lib/centreon/*_spec.rb'
      - run: sleep 30
      - run: docker-compose run puppet-ci bash -c 'curl -vvv http://172.17.0.1/centreon/api/index.php'
      - run: docker-compose run puppet-ci bash -c 'BEAKER_set=ci rspec spec/acceptance/*_spec.rb'
workflows:
  version: 2
  build-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/