# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker-compose up -d centreon-ci
          sleep 10
          docker-compose exec centreon-ci ps aux
workflows:
  version: 2
  build-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/