# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    docker:
      - image: circleci/ruby
    steps:
      - setup_remote_docker
      - checkout
      - run: docker-compose build puppet-ci
      - run: docker-compose run puppet-ci bash -c 'rspec lib/centreon/*_spec.rb'
      - run: docker-compose run puppet bash -c 'rspec lib/centreon/*_spec.rb'
      - codecov/upload:
          file: coverage/.resultset.jon
          flags: unittest
workflows:
  version: 2
  build-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/