HOSTS:
  centos-7-x64:
    roles:
      - default
    platform: el-7-x86_64
    hypervisor: docker
    docker_cmd: '["/usr/sbin/init"]'
    docker_image_commands:
      - 'yum install -y crontabs initscripts iproute openssl sysvinit-tools tar wget which ss gcc-c++'
      - 'systemctl mask getty@tty1.service'
    image: centos:7
    docker_preserve_image: true
    mount_folders:
      r10k:
        host_path: ./vendor
        container_path: /etc/puppetlabs/code
        opts: rw
      hiera:
        host_path: ./spec/fixtures/hieradata
        container_path: /etc/puppetlabs/code/environments/production/hieradata
        opts: ro
      module:
        host_path: .
        container_path: /etc/puppetlabs/code/environments/production/modules/hm_centreon
        opts: ro

CONFIG:
  type: foss
  trace_limit: 1000
#  log_level: verbose